kiplot:
  version: 1

outputs:

  - name: "gerbers"
    type: gerber
    dir: gerber
    options:
      # generic layer options
      exclude_edge_layer: false
      exclude_pads_from_silkscreen: false
      use_aux_axis_as_origin: false
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: true
      force_plot_invisible_refs_vals: false
      tent_vias: true
      check_zone_fills: true

      # gerber options
      line_width: 0.15
      subtract_mask_from_silk: true
      use_protel_extensions: true
      gerber_precision: 4.5
      create_gerber_job_file: true
      use_gerber_x2_attributes: true
      use_gerber_net_attributes: false

    layers:
      - layer: F.Cu
        suffix: F.Cu
      - layer: B.Cu
        suffix: B.Cu
      - layer: F.Paste
        suffix: F.Paste
      - layer: B.Paste
        suffix: B.Paste
      - layer: F.SilkS
        suffix: F.SilkS
      - layer: B.SilkS
        suffix: B.SilkS
      - layer: F.Mask
        suffix: F.Mask
      - layer: B.Mask
        suffix: B.Mask
      - layer: Edge.Cuts
        suffix: Edge.Cuts
        
  - name: gerber drills
    type: gerb_drill
    dir: gerber
    options:
      use_aux_axis_as_origin: false

        
